def test_cross_school_access_denied(client, teacher_a_token, school_b_class_id):
    r = client.get(f"/api/v1/classes/{school_b_class_id}", headers={"Authorization": f"Bearer {teacher_a_token}"})
    assert r.status_code == 403

def test_student_cannot_read_others_submission(...): ...
def test_expired_token_rejected(...): ...
def test_guardian_only_sees_linked_child(...): ...